# =========================================================================================
# OPENSTUDIOHUB
# Module: src/interfaces/qt/viewmodels/infrastructure_viewmodel.py
# Architectural role: MVVM ViewModel / studio infrastructure
# =========================================================================================

"""ViewModel for the studio infrastructure panel.

Encapsulates the Docker Compose generation and the lifecycle commands (SVN and
Kitsu). The View only renders service cards and forwards button presses here.
"""

import subprocess
from pathlib import Path

from PySide6.QtCore import Signal

from src.application.services.production_service import ProductionService
from src.infrastructure.dev_defaults import (
    DEV_KITSU_DB_PASSWORD,
    DEV_KITSU_INDEXER_KEY,
    DEV_KITSU_SECRET_KEY,
)
from src.interfaces.qt.viewmodels.base_viewmodel import BaseViewModel, StatusSink
from src.interfaces.qt.workers.infrastructure_workers import DockerWorker, KitsuSeederWorker
from src.interfaces.qt.workers.worker_manager import WorkerManager


class InfrastructureViewModel(BaseViewModel):
    operation_finished = Signal(bool, str)

    def __init__(
        self,
        config_factory,
        production_service: ProductionService,
        status_sink: StatusSink | None = None,
        parent=None,
    ) -> None:
        super().__init__(status_sink, parent)
        self.config_factory = config_factory
        self.production_service = production_service

        self.infra_dir = self.config_factory.get_workspace_root() / ".openstudio_infra"
        self.infra_dir.mkdir(parents=True, exist_ok=True)

        self.workers = WorkerManager(self)

    # ------------------------------------------------------------------
    # SVN lifecycle
    # ------------------------------------------------------------------
    def deploy_svn(self) -> None:
        self.report_status("Deploying Local SVN Server. Please wait...", "yellow")
        command = [
            "docker", "run", "-d",
            "--name", "openstudio_local_svn",
            "-p", "3690:3690",
            "elleflorio/svn-server",
        ]
        self._run_docker_worker(command)

    def stop_svn(self) -> None:
        self.report_status("Destroying SVN Server...", "yellow")
        subprocess.run(["docker", "stop", "openstudio_local_svn"], capture_output=True)
        subprocess.run(["docker", "rm", "openstudio_local_svn"], capture_output=True)
        self.report_status("SVN Server destroyed.", "green")

    # ------------------------------------------------------------------
    # Kitsu lifecycle
    # ------------------------------------------------------------------
    def deploy_kitsu(self) -> None:
        self.report_status("Generating the Docker Compose architecture for Kitsu. Please wait...", "yellow")

        db_dir = self.infra_dir / "db"
        db_dir.mkdir(exist_ok=True)
        pg_ctl = db_dir / "pg_ctl.conf"
        if not pg_ctl.exists():
            pg_ctl.write_text("# Auto-generated by the Open Studio Hub infrastructure\n")

        env_content = f"""COMPOSE_PROJECT_NAME=kitsu_local
ENV_FILE=env
KITSU_VERSION=latest
ZOU_VERSION=latest
KV_HOST=redis
KV_PORT=6379
DB_HOST=db
DB_VERSION=18
DB_USERNAME=postgres
DB_PASSWORD={DEV_KITSU_DB_PASSWORD}
DB_DATABASE=zoudb
DB_DATA_PATH=/var/lib/data
ENABLE_JOB_QUEUE=True
PREVIEW_FOLDER=/opt/zou/previews
TMP_DIR=/tmp/zou
EVENT_STREAM_HOST=zou-event
PORT=80
INDEXER_VERSION=v1.31
INDEXER_KEY={DEV_KITSU_INDEXER_KEY}
INDEXER_HOST=indexer
INDEXER_PORT=7700
USER_LIMIT=200
SECRET_KEY={DEV_KITSU_SECRET_KEY}
"""
        (self.infra_dir / "env").write_text(env_content)

        compose_content = self._compose_template()
        (self.infra_dir / "docker-compose.yml").write_text(compose_content)

        command = ["docker", "compose", "--env-file", "env", "up", "-d"]
        self._run_docker_worker(command, cwd=self.infra_dir)

    def stop_kitsu(self) -> None:
        self.report_status("Tearing down Kitsu Stack...", "yellow")
        command = ["docker", "compose", "down", "-v"]
        self._run_docker_worker(command, cwd=self.infra_dir)

    # ------------------------------------------------------------------
    # Database seeders
    # ------------------------------------------------------------------
    def run_seeder(self, action: str) -> None:
        if self.workers.is_running("seeder"):
            self.report_status("A seeder is already running...", "red")
            return
        self.report_status("Running Seeder against the Database...", "yellow")
        worker = KitsuSeederWorker(self.production_service, action)
        worker.finished_signal.connect(self._on_worker_finished)
        self.workers.start("seeder", worker)

    def _run_docker_worker(self, command: list, cwd: Path | None = None) -> None:
        if self.workers.is_running("docker"):
            self.report_status("A docker operation is already running...", "red")
            return
        worker = DockerWorker(command, cwd)
        worker.finished_signal.connect(self._on_worker_finished)
        self.workers.start("docker", worker)

    def _on_worker_finished(self, success: bool, message: str) -> None:
        color = "green" if success else "red"
        self.report_status(message, color)
        self.operation_finished.emit(success, message)

    @staticmethod
    def _compose_template() -> str:
        return r"""x-base: &base
    restart: always
    networks:
        - internal

x-env: &env
    env_file:
        - ${ENV_FILE:-./env}

x-backend-volumes: &backend_volumes
    volumes:
        - 'previews:${PREVIEW_FOLDER:?}'
        - 'tmp:${TMP_DIR:-/tmp/zou}'

services:
    kitsu:
        <<: [*base, *env]
        container_name: ${COMPOSE_PROJECT_NAME:?}-frontend
        image: registry.gitlab.com/mathbou/docker-cgwire/kitsu:${KITSU_VERSION:-latest}
        ports:
            - "8080:80"
        depends_on:
            zou-app:
                condition: service_healthy
            zou-event:
                condition: service_started
            zou-jobs:
                condition: service_started

    zou-app:
        <<: [*base,*env, *backend_volumes]
        container_name: ${COMPOSE_PROJECT_NAME:?}-zou-app
        image: registry.gitlab.com/mathbou/docker-cgwire/zou:${ZOU_VERSION:-latest}
        depends_on:
            db:
                condition: service_healthy
            indexer:
                condition: service_healthy
        command: >
            sh -c "zou init-db || true &&
                   zou upgrade-db || true &&
                   zou init-data || true &&
                   gunicorn --error-logfile - --access-logfile - -w 3 -k gevent -b :5000 zou.app:app"
        healthcheck:
            test: "curl -s -f http://localhost:5000 | grep -q '\"api\":\"Zou\"'"

    zou-event:
        <<: [*base, *env]
        container_name: ${COMPOSE_PROJECT_NAME:?}-zou-event
        image: registry.gitlab.com/mathbou/docker-cgwire/zou:${ZOU_VERSION:-latest}
        depends_on:
            redis:
                condition: service_started
            zou-app:
                condition: service_healthy
        command: "gunicorn --error-logfile - --access-logfile - -w 1 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -b :5001 zou.event_stream:app"
        healthcheck:
            test: "curl -s -f http://localhost:5001 | grep -q '\"api\":\"Zou\"'"

    zou-jobs:
        <<: [*base, *env, *backend_volumes]
        container_name: ${COMPOSE_PROJECT_NAME:?}-zou-jobs
        image: registry.gitlab.com/mathbou/docker-cgwire/zou:${ZOU_VERSION:-latest}
        depends_on:
            zou-app:
                condition: service_healthy
        command: "rq worker -c zou.job_settings"
        healthcheck:
            test: "rq info -u redis://${KV_HOST:?}:${KV_PORT:-6379}/3 -W | grep -v -q '0 workers'"

    db:
        <<: *base
        container_name: ${COMPOSE_PROJECT_NAME:?}-db-${DB_VERSION:?}
        image: postgres:${DB_VERSION:?}-alpine
        volumes:
            - 'db:${DB_DATA_PATH:?}'
            - ./db/pg_ctl.conf:/etc/postgresql/${DB_VERSION:?}/main/pg_ctl.conf:ro
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD:?}
            - POSTGRES_DB=zoudb
        healthcheck:
            test: "pg_isready -d zoudb -U postgres"

    redis:
        <<: *base
        container_name: ${COMPOSE_PROJECT_NAME:?}-redis
        image: redis:alpine
        volumes:
            - 'redis:/data'

    indexer:
        <<: *base
        container_name: ${COMPOSE_PROJECT_NAME:?}-indexer-${INDEXER_VERSION:?}
        image: getmeili/meilisearch:${INDEXER_VERSION:?}
        volumes:
            - 'indexer:/meili_data'
        environment:
            - MEILI_MASTER_KEY=${INDEXER_KEY:?}
        healthcheck:
            test: "curl -s -f http://localhost:${INDEXER_PORT:-7700}/health | grep -q '{\"status\":\"available\"}'"

volumes:
    db:
        name: ${COMPOSE_PROJECT_NAME:?}-db-${DB_VERSION:?}
    redis:
        name: ${COMPOSE_PROJECT_NAME:?}-redis
    previews:
        name: ${COMPOSE_PROJECT_NAME:?}-previews
    tmp:
        name: ${COMPOSE_PROJECT_NAME:?}-tmp
    indexer:
        name: ${COMPOSE_PROJECT_NAME:?}-indexer-${INDEXER_VERSION:?}

networks:
    internal:
        name: ${COMPOSE_PROJECT_NAME:?}-internal
"""
