schema_version = "1.0.0"
id = "openstudio_toolkit"
version = "0.5.0"
name = "OpenStudio Toolkit"
tagline = "QA tools and validation, CVS autoupdate"
maintainer = "Ernesto Del Valle Macuare"
type = "add-on"
blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]
