# =========================================================================================
# OPENSTUDIOHUB
# Module: src/application/services/vault_service.py
# Architectural role: Application service / software vault inventory
# =========================================================================================

"""Software vault inventory service.

Loads and persists the canonical ``VaultManifest`` aggregate through the
``VaultManifestRepository`` port, including the Day-0 default seeding.
"""

from pathlib import Path
from typing import Any, Dict

from src.application.ports import VaultManifestRepository
from src.domain.vault.manifest import VaultManifest

_DEFAULT_SEED: Dict[str, Any] = {
    "5.1.2": {
        "categories": {
            "templates": {
                "Macuare_Estudio_Base": {
                    "version": "1.0",
                    "description": "Default studio template generated by the Hub.",
                    "mandatory": True,
                    "requires": [],
                }
            },
            "addons": {},
        }
    }
}


class VaultService:
    def __init__(self, repository: VaultManifestRepository) -> None:
        self._repository = repository
        self._manifest: VaultManifest = VaultManifest()

    @property
    def manifest_path(self) -> Path:
        return self._repository.path()

    @property
    def vault_root(self) -> Path:
        return self._repository.path().parent

    def load_inventory(self) -> dict:
        """Load the normalized manifest, seeding a default when absent."""
        if not self.manifest_path.exists():
            self.save_inventory(_DEFAULT_SEED)

        self._manifest = self._repository.load()
        return self._manifest.versions

    def save_inventory(self, payload: dict) -> bool:
        """Persist the manifest state to disk."""
        self._manifest = VaultManifest.from_dict(payload)
        return self._repository.save(self._manifest)

    def current_inventory(self) -> dict:
        """Return the in-memory normalized manifest without forcing disk I/O."""
        return self._manifest.versions
